services:
  db:
    image: postgres:17
    container_name: taskforge-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskforge
    ports:
      - "5432:5432"
    volumes:
      - taskforge_pgdata:/var/lib/postgresql/data
    networks:
      - taskforge-network

  app:
    build: .
    container_name: taskforge-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://taskforge-db.c9ag6qwikwj0.us-east-2.rds.amazonaws.com:5432/taskforge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - taskforge-network

volumes:
  taskforge_pgdata:

networks:
  taskforge-network:
    driver: bridge