spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskforge
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 8080